import Head from "next/head";

import Header from "./header";

export default function Layout({ children, router }) {
  return (
    <>
      <Head>
        <title>Rest Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen bg-slate-50 dark:bg-slate-900 text-black dark:text-slate-50">
        <Header path={router.asPath} />
        <main className="flex-grow py-8">{children}</main>
      </div>
    </>
  );
}
